Models/Period.cs
namespace MSAWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("msa.Periods")]
    public partial class Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Period()
        {
            RatingHistories = new HashSet<RatingHistory>();
            SuggestionHistories = new HashSet<SuggestionHistory>();
        }

        public long Id { get; set; }

        public int Length { get; set; }

        public int? Count { get; set; }

        public bool IsActive { get; set; }

        public bool IsPending { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingHistory> RatingHistories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuggestionHistory> SuggestionHistories { get; set; }
    }
}

Controllers/PeriodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MSAWeb.Models;
using MSAWeb.Classes;
using System.Net;
using OfficeOpenXml;
using System.IO;
using System.Web;

namespace MSAWeb.Controllers
{
    public class PeriodController : Controller
    {
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.NotificationMessage = TempData["Message"];
                ViewBag.NotificationTitle = (bool)TempData["Result"] ? "Success" : "Error";
                ViewBag.NotificationType = (bool)TempData["Result"] ? "notice" : "error";
            }
            try
            {
                ViewBag.Data = DatabaseManager.Instance.Periods.ToList();
                ViewBag.ActiveFound = false;
                ViewBag.PendingFound = false;
                var active = DatabaseManager.Instance.Periods.Where(x => x.IsActive).FirstOrDefault();
                var pending = DatabaseManager.Instance.Periods.Where(x => x.IsPending).FirstOrDefault();
                if (active != null)
                {
                    ViewBag.ActiveFound = true;
                    ViewBag.ActivePeriod = active;
                }
                else if (pending != null)
                {
                    ViewBag.PendingFound = true;
                    ViewBag.PendingUsers = (from a in DatabaseManager.Instance.Users
                                            where !DatabaseManager.Instance.RatingHistories.Any(x => x.PeriodId == pending.Id && x.UserId == a.Id)
                                            select a).ToList();
                }
            }
            catch(Exception ex)
            {
                ViewBag.Data = new List<Period>();
                ViewBag.NotificationMessage = "Periods could not be loaded. Inner message: " + ex.Message;
                ViewBag.NotificationTitle = "Error";
                ViewBag.NotificationType = "error";
            }
            return View();
        }

        [HttpGet]
        public ActionResult PrepareAdd()
        {
            return PartialView("_Add", new Period());
        }

        [HttpPost]
        public ActionResult Add(Period period)
        {
            period.Count = 0;
            period.IsActive = false;
            period.IsPending = true;
            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseManager.Instance.Periods.Add(period);
                    DatabaseManager.Instance.SaveChanges();
                    TempData["Message"] = "Period is added.";
                    TempData["Result"] = true;
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "Period could not be added. Inner message: " + ex.Message;
                    TempData["Result"] = false;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PrepareCancel(long id)
        {
            var period = DatabaseManager.Instance.Periods.Find(id);
            if (period == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Json("Period is not found.", JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Cancel", period);
        }

        [HttpPost]
        public ActionResult Cancel(Period period)
        {
            try
            {
                var old = DatabaseManager.Instance.Periods.Find(period.Id);
                old.IsActive = false;
                old.IsPending = false;
                DatabaseManager.Instance.SaveChanges();
                TempData["Message"] = "Period is cancelled.";
                TempData["Result"] = true;
            }
            catch (Exception ex)
            {
                TempData["Message"] = "Period could not be cancelled. Inner message: " + ex.Message;
                TempData["Result"] = false;
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Download(long id)
        {
            var stream = new MemoryStream();
            var name = "rating.xlsx";
            var type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            try
            {
                using (var package = new ExcelPackage())
                {
                    package.Workbook.Worksheets.Add("rating");
                    var sheet = package.Workbook.Worksheets[1];
                    sheet.Cells[1, 3].Value = "User Info";
                    sheet.Cells[1, 3].Style.Font.Bold = true;
                    sheet.Cells[1, 3].Style.Font.UnderLine = true;
                    sheet.Cells[1, 3].Style.Font.Size = 14;
                    sheet.Cells[5, 3].Value = "Restaurant List";
                    sheet.Cells[5, 3].Style.Font.Bold = true;
                    sheet.Cells[5, 3].Style.Font.UnderLine = true;
                    sheet.Cells[5, 3].Style.Font.Size = 14;
                    sheet.Cells[2, 1].Value = "Id:";
                    sheet.Cells[3, 1].Value = "Name:";
                    sheet.Cells[4, 1].Value = "Surname:";
                    sheet.Cells[6, 1].Value = "Id";
                    sheet.Cells[6, 2].Value = "Title";
                    sheet.Cells[6, 3].Value = "Transportation";
                    sheet.Cells[6, 4].Value = "Weather Dependency";
                    sheet.Cells[6, 5].Value = "Taste (1-10)";
                    sheet.Cells[6, 6].Value = "Speed (1-10)";
                    sheet.Cells[6, 7].Value = "Service (1-10)";
                    var user = DatabaseManager.Instance.Users.Find(id);
                    sheet.Cells[2, 2].Value = user.Id;
                    sheet.Cells[3, 2].Value = user.Name;
                    sheet.Cells[4, 2].Value = user.Surname;
                    int location = 7;   // starting point of restaurant list in document
                    foreach (var restaurant in DatabaseManager.Instance.Restaurants.ToList().OrderBy(x => x.Title))
                    {
                        sheet.Cells[location, 1].Value = restaurant.Id;
                        sheet.Cells[location, 2].Value = restaurant.Title;
                        sheet.Cells[location, 3].Value = restaurant.CarOrWalk == "C" ? "By Car" : "By Walking";
                        sheet.Cells[location, 4].Value = restaurant.WeatherDependency == true ? "Dependent" : "Independent";
                        location++;
                    }
                    sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
                    package.SaveAs(stream);
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = "Rating document could not be downloaded. Inner message: " + ex.Message;
                TempData["Result"] = false;
                return RedirectToAction("Index");
            }
            stream.Position = 0;
            var result = new FileStreamResult(stream, type);
            result.FileDownloadName = name;
            return result;
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if(file != null && file.ContentLength > 0)
            {
                try
                {
                    using(var package = new ExcelPackage())
                    {
                        package.Load(file.InputStream);
                        var sheet = package.Workbook.Worksheets[1];
                        long userId = Convert.ToInt64(sheet.Cells[2, 2].Value);
                        long periodId = DatabaseManager.Instance.Periods.Where(x => x.IsPending).FirstOrDefault().Id;
                        int location = 7;   // starting point of restaurant list in document
                        for (int i = 0; i < DatabaseManager.Instance.Restaurants.Count(); i++)
                        {
                            var rating = new RatingHistory();
                            rating.UserId = userId;
                            rating.PeriodId = periodId;
                            rating.RestaurantId = Convert.ToInt64(sheet.Cells[location + i, 1].Value);
                            rating.Taste = GetExcelValue(sheet.Cells[location + i, 5].Value);
                            rating.Speed = GetExcelValue(sheet.Cells[location + i, 6].Value);
                            rating.Service = GetExcelValue(sheet.Cells[location + i, 7].Value);
                            DatabaseManager.Instance.RatingHistories.Add(rating);
                        }
                        DatabaseManager.Instance.SaveChanges();
                        var pendingUsersCount = (from a in DatabaseManager.Instance.Users
                                                 where !DatabaseManager.Instance.RatingHistories.Any(x => x.PeriodId == periodId && x.UserId == a.Id)
                                                 select a).Count();
                        if (pendingUsersCount == 0)
                        {
                            var period = DatabaseManager.Instance.Periods.Find(periodId);
                            period.IsPending = false;
                            period.IsActive = true;
                        }
                        DatabaseManager.Instance.SaveChanges();
                        TempData["Message"] = "File is uploaded.";
                        TempData["Result"] = true;
                    }
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "File could not be uploaded. Inner message: " + ex.Message;
                    TempData["Result"] = false;
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index"); ;
        }

        private int? GetExcelValue(dynamic cell)
        {

Views/Period/Index.cshtml
@{
    ViewBag.Title = "Periods";
}

@model MSAWeb.Models.Period

<div class="row">
    <div class="col-md-12 col-xs-12 text-center">
        <h2>Periods</h2>
    </div>
</div>

<div class="row">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Length</th>
                    <th>Count</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var period in ViewBag.Data as List<MSAWeb.Models.Period>)
                {
                    string status = String.Empty;
                    if (period.IsActive) { status = "In Progress"; }
                    else if (period.IsPending) { status = "Pending"; }
                    else if(period.Count < period.Length) { status = "Cancelled"; }
                    else { status = "Completed"; }
                    <tr>
                        <td>@period.Length day(s)</td>
                        <td>@period.Count day(s)</td>
                        <td>@status</td>
                        @if (period.IsActive || period.IsPending)
                        {
                            <td><a href="#" onclick="processPeriod('/Period/PrepareCancel/'+@period.Id)"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@if (!ViewBag.ActiveFound && !ViewBag.PendingFound)
{
<div class="row">
    <div class="col-md-12 col-xs-12 text-center">
        <button type="button" class="btn btn-info" onclick="processPeriod('/Period/PrepareAdd')">Start Period</button>
    </div>
</div>
}
else
{
    if (ViewBag.PendingFound)
    {
<div class="row">
    <h3 class="text-center">Pending Users</h3>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Download</th>
                    <th>Upload</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in ViewBag.PendingUsers as List<MSAWeb.Models.User>)
                {
                    <tr>
                        <td>@user.Name</td>
                        <td>@user.Surname</td>
                        <td><a href="@Url.Action("Download", "Period", new { id = user.Id } )"><span class="glyphicon glyphicon-download" aria-hidden="true"></span></a></td>
                        <td><a href="#" data-toggle="modal" data-target="#upload-modal"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
    }
}

<div class="row">
    <div class="col-md-12 col-xs-12 text-left">
        <button class="btn btn-primary btn-info" type="button" onclick="location.href='@Url.Action("Index", "Home")'">&lt; Back</button>
    </div>
</div>

<div class="modal fade" id="crud-modal">
    <div class="modal-dialog">
        <div id="modal-wrapper" class="modal-content">
            <!-- modal burayi dolduracak -->
        </div>
    </div>
</div>

<div class="modal fade" id="upload-modal">
    <div class="modal-dialog">
        <div id="modal-wrapper" class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Upload Rating File</h3>
            </div>
            @using (Html.BeginForm("Upload", "Period", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="modal-body">
                    <label for="file">Rating File:</label>
                    <input type="file" name="file" id="file" />
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit">Upload</button>
                    <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        var message = '@ViewBag.NotificationMessage';
        if (message != '') {
            $.growl({
                title: '@ViewBag.NotificationTitle',
                message: message,
                style: '@ViewBag.NotificationType'
            });
        }
    });
</script>

<script type="text/javascript">
    function processPeriod(path) {
        $.ajax({
            method: 'GET',
            url: path,
            success: function (data) {
                $('#modal-wrapper').html(data);
                $('#crud-modal').modal();
            }
        })
    }
</script>

Views/Period/_Add.cshtml
@model MSAWeb.Models.Period

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add Period</h3>
</div>
@using (Ajax.BeginForm("Add", "Period", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.Count)
        @Html.HiddenFor(x => x.IsActive)
        @Html.HiddenFor(x => x.IsPending)

        @Html.Label("Length", "Length (days)")
        @Html.TextBoxFor(x => x.Length, new { @class = "form-control" })
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Save</button>
        <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
    </div>
}

Views/Period/_Cancel.cshtml
@model MSAWeb.Models.Period

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Cancel Period</h3>
</div>
@using (Ajax.BeginForm("Cancel", "Period", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)

        @Html.LabelFor(x => x.Length)
        @Html.TextBoxFor(x => x.Length, new { @class = "form-control", @readonly = "true" })

        @Html.LabelFor(x => x.Count)
        @Html.TextBoxFor(x => x.Count, new { @class = "form-control", @readonly = "true" })

        @Html.LabelFor(x => x.IsActive)
        @Html.CheckBoxFor(x => x.IsActive, new { @class = "checkbox", @disabled = "disabled" })

        @Html.LabelFor(x => x.IsPending)
        @Html.CheckBoxFor(x => x.IsPending, new { @class = "checkbox", @disabled = "disabled" })
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger" type="submit">Cancel</button>
        <button class="btn btn-default" type="button" data-dismiss="modal">Back</button>
    </div>
}