Models/Restaurant.cs
namespace MSAWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("msa.Restaurants")]
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            RatingHistories = new HashSet<RatingHistory>();
            SuggestionHistories = new HashSet<SuggestionHistory>();
        }

        public long Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        [StringLength(1)]
        public string CarOrWalk { get; set; }

        public bool WeatherDependency { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingHistory> RatingHistories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuggestionHistory> SuggestionHistories { get; set; }
    }
}

Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MSAWeb.Models;
using System.Net;
using MSAWeb.Classes;

namespace MSAWeb.Controllers
{
    public class RestaurantController : Controller
    {
        public ActionResult Index()
        {
            if(TempData["Message"] != null)
            {
                ViewBag.NotificationMessage = TempData["Message"];
                ViewBag.NotificationTitle = (bool)TempData["Result"] ? "Success" : "Error";
                ViewBag.NotificationType = (bool)TempData["Result"] ? "notice" : "error";
            }
            try
            {
                ViewBag.Data = DatabaseManager.Instance.Restaurants.ToList();
            }
            catch(Exception ex)
            {
                ViewBag.Data = new List<Restaurant>();
                ViewBag.NotificationMessage = "Restaurants could not be loaded. Inner message: " + ex.Message;
                ViewBag.NotificationTitle = "Error";
                ViewBag.NotificationType = "error";
            }
            return View();
        }

        [HttpGet]
        public ActionResult PrepareAdd()
        {
            if (!CheckPeriod())
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Adding restaurant is not allowed while there is an active/pending period.", JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Add", new Restaurant());
        }

        [HttpPost]
        public ActionResult Add(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseManager.Instance.Restaurants.Add(restaurant);
                    DatabaseManager.Instance.SaveChanges();
                    TempData["Message"] = "Restaurant is added.";
                    TempData["Result"] = true;
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "Restaurant could not be added. Inner message: " + ex.Message;
                    TempData["Result"] = false;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PrepareEdit(long id)
        {
            if (!CheckPeriod())
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Editing restaurant is not allowed while there is an active/pending period.", JsonRequestBehavior.AllowGet);
            }
            var restaurant = DatabaseManager.Instance.Restaurants.Find(id);
            if (restaurant == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Json("Restaurant is not found.", JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Edit", restaurant);
        }

        [HttpPost]
        public ActionResult Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                var old = DatabaseManager.Instance.Restaurants.Find(restaurant.Id);
                old.Title = restaurant.Title;
                old.CarOrWalk = restaurant.CarOrWalk;
                old.WeatherDependency = restaurant.WeatherDependency;
                try
                {
                    DatabaseManager.Instance.SaveChanges();
                    TempData["Message"] = "Restaurant is edited.";
                    TempData["Result"] = true;
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "Restaurant could not be edited. Inner message: " + ex.Message;
                    TempData["Result"] = false;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PrepareDelete(long id)
        {
            if (!CheckPeriod())
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Deleting restaurant is not allowed while there is an active/pending period.", JsonRequestBehavior.AllowGet);
            }
            var restaurant = DatabaseManager.Instance.Restaurants.Find(id);
            if (restaurant == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Json("Restaurant is not found.", JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Delete", restaurant);
        }

        [HttpPost]
        public ActionResult Delete(Restaurant restaurant)
        {
            try
            {
                DatabaseManager.Instance.Restaurants.Remove(DatabaseManager.Instance.Restaurants.Find(restaurant.Id));
                DatabaseManager.Instance.SaveChanges();
                TempData["Message"] = "Restaurant is deleted.";
                TempData["Result"] = true;
            }
            catch (Exception ex)
            {
                TempData["Message"] = "Restaurant could not be deleted. Inner message: " + ex.Message;
                TempData["Result"] = false;
            }
            return RedirectToAction("Index");
        }

        private bool CheckPeriod()
        {
            var active = DatabaseManager.Instance.Periods.Where(x => x.IsActive).FirstOrDefault();
            var pending = DatabaseManager.Instance.Periods.Where(x => x.IsPending).FirstOrDefault();
			return active == null && pending == null;
        }
    }
}

Views/Restaurant/Index.cshtml
@{
    ViewBag.Title = "Restaurants";
}

@model MSAWeb.Models.Restaurant

<div class="row">
    <div class="col-md-12 text-center">
        <h2>Restaurants</h2>
    </div>
</div>

<div class="row">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Transportation</th>
                    <th>Weather Dependency</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var restaurant in ViewBag.Data as List<MSAWeb.Models.Restaurant>)
                {
                    string transportation = restaurant.CarOrWalk == "C" ? "By Car" : "By Walking";
                    string dependency = restaurant.WeatherDependency ? "Dependent" : "Independent";
                    <tr>
                        <td>@restaurant.Title</td>
                        <td>@transportation</td>
                        <td>@dependency</td>
                        <td><a href="#" onclick="processRestaurant('/Restaurant/PrepareEdit/'+@restaurant.Id)"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                        <td><a href="#" onclick="processRestaurant('/Restaurant/PrepareDelete/'+@restaurant.Id)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-xs-6 text-left">
        <button class="btn btn-primary btn-info" type="button" onclick="location.href='@Url.Action("Index", "Home")'">&lt; Back</button>
    </div>
    <div class="col-md-6 col-xs-6 text-right">
        <button type="button" class="btn btn-info" onclick="processRestaurant('/Restaurant/PrepareAdd')">Add Restaurant</button>
    </div>
</div>

<div class="modal fade" id="crud-modal">
    <div class="modal-dialog">
        <div id="modal-wrapper" class="modal-content">
            <!-- modal burayi dolduracak -->
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        var message = '@ViewBag.NotificationMessage';
        if (message != '') {
            $.growl({
                title: '@ViewBag.NotificationTitle',
                message: message,
                style: '@ViewBag.NotificationType'
            });
        }
    });
</script>

<script type="text/javascript">
    function processRestaurant(path) {
        $.ajax({
            method: 'GET',
            url: path,
            success: function (data) {
                $('#modal-wrapper').html(data);
                $('#crud-modal').modal();
            },
            error: function (data) {
                var message = data.responseText;
                $.growl({
                    title: 'Error',
                    message: message,
                    style: 'error'
                });
            }
        })
    }
</script>

Views/Restaurant/_Add.cshtml
@model MSAWeb.Models.Restaurant

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add Restaurant</h3>
</div>
@using (Ajax.BeginForm("Add", "Restaurant", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)

        @Html.LabelFor(x => x.Title)
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })

        @Html.LabelFor(x => x.CarOrWalk)
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "C", new { @class = "radio" })
            By Car
            </label>
        </div>
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "W", new { @class = "radio" })
            By Walking
            </label>
        </div>

        @Html.LabelFor(x => x.WeatherDependency)
        @Html.CheckBoxFor(x => x.WeatherDependency, new { @class = "checkbox" })
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Save</button>
        <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
    </div>
}

Views/Restaurant/_Delete.cshtml
@model MSAWeb.Models.Restaurant

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Delete Restaurant</h3>
</div>
@using (Ajax.BeginForm("Delete", "Restaurant", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)

        @Html.LabelFor(x => x.Title)
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @readonly = "true" })

        @Html.LabelFor(x => x.CarOrWalk)
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "C", new { @class = "radio", @disabled = "disabled" })
            By Car
            </label>
        </div>
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "W", new { @class = "radio", @disabled = "disabled" })
            By Walking
            </label>
        </div>

        @Html.LabelFor(x => x.WeatherDependency)
        @Html.CheckBoxFor(x => x.WeatherDependency, new { @class = "checkbox", @disabled = "disabled" })
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger" type="submit">Remove</button>
        <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
    </div>
}

Views/Restaurant/_Edit.cshtml
@model MSAWeb.Models.Restaurant

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Edit Restaurant</h3>
</div>
@using (Ajax.BeginForm("Edit", "Restaurant", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)

        @Html.LabelFor(x => x.Title)
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })

        @Html.LabelFor(x => x.CarOrWalk)
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "C", new { @class = "radio" })
            By Car
            </label>
        </div>
        <div class="radio">
            <label>
            @Html.RadioButtonFor(x => x.CarOrWalk, "W", new { @class = "radio" })
            By Walking
            </label>
        </div>

        @Html.LabelFor(x => x.WeatherDependency)
        @Html.CheckBoxFor(x => x.WeatherDependency, new { @class = "checkbox" })
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Save</button>
        <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
    </div>
}